#!/bin/sh
##############################################################
# Install scripts into a directory of your choice.
#
# A symbolic link is created for each script into the 
# specified directory.
##############################################################
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 install_directory"
    echo "       $0 ~/bin"
    echo "install_directory should be a directory that is on your PATH"
    exit 1
fi
INSTALL_DIR=$1
if [ ! -d ${INSTALL_DIR} ]; then
    echo "Error: ${INSTALL_DIR} is not a directory"
    echo "Usage: $0 install_directory"
    echo "       $0 ~/bin"
    exit 1
fi
echo "Installing scripts into ${INSTALL_DIR}"
SCRIPTS=`find .  \( -type l -or -type f \) -perm +111 | grep -v \.git`
for a in ${SCRIPTS}; do
    SCRIPT=${INSTALL_DIR}/`basename $a`
    if [ -L "${SCRIPT}" ]; then
        echo "\t${SCRIPT} is already linked"
    elif [ -f "${SCRIPT}" ]; then
        echo "${SCRIPT} already exists as a file. Copying..."
        cp $a "${INSTALL_DIR}"
    else
        echo "\tLinking $a"
        ln -s `pwd`/$a "${INSTALL_DIR}"
    fi
done

ln -s `pwd`/utility/_upgradeNpmPackage "${INSTALL_DIR}"

# Add path to zsh (OS X 10.15+)
if [[ -e ~/.zshenv ]]; then
    grep DEV_TOOLS ~/.zshenv > /dev/null
    if [ "$?" -ne 0 ]; then
        echo "\nexport DEV_TOOLS=${INSTALL_DIR}" >> ~/.zshenv
    fi
fi

# Add path to bash (OS X 10.14)
if [[ -e ~/.bash_profile ]]; then
    grep DEV_TOOLS ~/.bash_profile > /dev/null
    if [ "$?" -ne 0 ]; then
        echo "\nexport DEV_TOOLS=${INSTALL_DIR}" >> ~/.bash_profile
    fi
fi

echo "Installing setup files"
cp $PWD/setup/subversion/config ~/.subversion/config
cp $PWD/setup/maven/settings.xml ~/.m2/settings.xml

exit 0
